% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Nov-2016 16:15:37
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('RandomWalkData.mat');

randomWalk = saveVarsMat.randomWalk; % <1000x2 double> too many elements

clear saveVarsMat;


plot(randomWalk(:,1), randomWalk(:,2),'DisplayName','randomWalk')
