% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Nov-2016 18:35:51
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('Statistics100.mat');

INFECTION_RATE = 0.2;

MOVEMENT_RATE = 0.3;

RECOVERY_RATE = 0.005;

statistics = saveVarsMat.statistics; % <521x3 double> too many elements

clear saveVarsMat;

PlotStatistics(statistics, MOVEMENT_RATE, INFECTION_RATE, RECOVERY_RATE);